CREATE TABLE USER_INFO
(		
		SEQ				NUMBER(10),
		EMAIL			VARCHAR2(100),
		DEPARTURE_DATE	VARCHAR2(100),
		CREATE_DATE		DATE,
		UPDATE_DATE		DATE,
		CONSTRAINT SEQ_PK PRIMARY KEY (SEQ)
);
COMMENT ON COLUMN USER_INFO.EMAIL IS 'Email';
COMMENT ON COLUMN USER_INFO.DEPARTURE_DATE IS '출국일자';
COMMENT ON COLUMN USER_INFO.CREATE_DATE IS '생성일';
COMMENT ON COLUMN USER_INFO.UPDATE_DATE IS '수정일';

-- DROP SEQUENCE USER_INFO_SEQ;
--CREATE SEQUENCE USER_INFO_SEQ INCREMENT BY 1 START WITH 1;

INSERT INTO USER_INFO(SEQ, EMAIL, DEPARTURE_DATE, CREATE_DATE)
     VALUES (USER_INFO_SEQ.NEXTVAL
           , 'test@naver.com'
           , '20230819'
           , SYSDATE);